language: node_js
node_js:
   - "5.5.0"

script:
  - grunt protractor_webdriver
  - node_modules/.bin/protractor test/e2e/conf.js --browser=firefox
  - grunt karma

before_install:
  - npm install -g grunt-cli

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./node_modules/protractor/bin/webdriver-manager update --standalone
  - npm start &
  - sleep 5

install:
  - npm install
